/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Doc;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocControllerApi
 */
@Ignore
public class DocControllerApiTest {

    private final DocControllerApi api = new DocControllerApi();

    
    /**
     * deleteDoc
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDocUsingDELETETest() throws ApiException {
        Long id = null;
        Long response = api.deleteDocUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * getDocument
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDocumentUsingGETTest() throws ApiException {
        Long id = null;
        Doc response = api.getDocumentUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * postDoc
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postDocUsingPOSTTest() throws ApiException {
        Doc doc = null;
        Doc response = api.postDocUsingPOST(doc);

        // TODO: test validations
    }
    
    /**
     * putDoc
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putDocUsingPUTTest() throws ApiException {
        Doc doc = null;
        Doc response = api.putDocUsingPUT(doc);

        // TODO: test validations
    }
    
    /**
     * restCall
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void restCallUsingGETTest() throws ApiException {
        Long id = null;
        Doc response = api.restCallUsingGET(id);

        // TODO: test validations
    }
    
}
